development:
  endpoint: http://ubuntu-dev:8081/api/v1
  api_key: <%= ENV['SORTARY_API_KEY'] -%>
demo:
  endpoint: <%= ENV['SORTARY_ENDPOINT'] -%>
  api_key: <%= ENV['SORTARY_API_KEY'] -%>
staging:
  endpoint: <%= ENV['SORTARY_ENDPOINT'] -%>
  api_key: <%= ENV['SORTARY_API_KEY'] -%>