development:
  endpoint: http://ubuntu-dev:8081/api/v1
  api_key: 46181685de0c22b5169a6519861eced18f9a0a26

#<%= ENV['SORTARY_ENDPOINT'] -%>
#<%= ENV['SORTARY_API_KEY'] -%>
demo:
  endpoint: http://demo.sortary.com/api/v1
  api_key: 46181685de0c22b5169a6519861eced18f9a0a26
staging:
  endpoint: http://s.sortary.com/api/v1
  api_key: 46181685de0c22b5169a6519861eced18f9a0a26